[package]
name = "ort-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = "0.60.1"
cc = "1.0.73"
flate2 = "1.0.24"
tar = "0.4.38"
ureq = "2.5.0"
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }
