[package]
name = "artspace-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
artspace-core = { version = "0.1.0", path = "../core" }
clap = { version = "3.2.16", features = ["derive"] }
ndarray-npy = "0.8.1"
